# Generated by Django 2.2.4 on 2021-03-16 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=400)),
                ('estado', models.BooleanField()),
                ('puntos', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id_quizz', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Quizz',
                'verbose_name_plural': 'Quizz',
            },
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=400)),
                ('estado', models.BooleanField()),
                ('correcta', models.BooleanField()),
                ('id_pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_respuesta_pregunta', to='ques.Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='QuizzUsuario',
            fields=[
                ('id_quizz_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_usuario_quizz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QuizzUsuario',
                'verbose_name_plural': 'QuizzUsuarios',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_quizz',
            field=models.ManyToManyField(related_name='fk_quizz_pregunta', to='ques.Quizz'),
        ),
    ]
